"""Initial setup

Revision ID: 4c0eec00a1bb
Revises: 
Create Date: 2026-03-16 13:08:46.269580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  
import geoalchemy2 


# revision identifiers, used by Alembic.
revision: str = '4c0eec00a1bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('ROOM', 'STAIRS', 'HALLWAY', 'INFO_TERMINAL', name='nodetype'), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_floor'), 'node', ['floor'], unique=False)
    op.create_index(op.f('ix_node_name'), 'node', ['name'], unique=True)
    op.create_table('wall',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wall_floor'), 'wall', ['floor'], unique=False)
    op.create_table('edge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_node_id', sa.Integer(), nullable=False),
    sa.Column('target_node_id', sa.Integer(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('CORRIDOR', 'STAIRS', 'ELEVATOR', 'DOOR', name='edgetype'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['source_node_id'], ['node.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edge_floor'), 'edge', ['floor'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_edge_floor'), table_name='edge')
    op.drop_table('edge')
    op.drop_index(op.f('ix_wall_floor'), table_name='wall')
    op.drop_table('wall')
    op.drop_index(op.f('ix_node_name'), table_name='node')
    op.drop_index(op.f('ix_node_floor'), table_name='node')
    op.drop_table('node')
    # ### end Alembic commands ###
