"""add elevator to enums

Revision ID: 7d809482cb17
Revises: 4c0eec00a1bb
Create Date: 2026-03-23 15:57:24.566423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  
import geoalchemy2
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '7d809482cb17'
down_revision: Union[str, Sequence[str], None] = '4c0eec00a1bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='nodetype',
        new_values=['ROOM', 'STAIRS', 'HALLWAY', 'INFO_TERMINAL', 'ELEVATOR'],
        affected_columns=[TableReference(table_schema='public', table_name='node', column_name='type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='nodetype',
        new_values=['ROOM', 'STAIRS', 'HALLWAY', 'INFO_TERMINAL'],
        affected_columns=[TableReference(table_schema='public', table_name='node', column_name='type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
