"""change wall geom to polygon

Revision ID: 9b16ea0a44cd
Revises: 7d809482cb17
Create Date: 2026-03-25 20:38:40.299349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '9b16ea0a44cd'
down_revision: Union[str, Sequence[str], None] = '7d809482cb17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('node', 'geom',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POINT', dimension=2, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               type_=geoalchemy2.types.Geometry(geometry_type='POINT', srid=3857, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'),
               existing_nullable=True)
    op.alter_column('wall', 'geom',
               existing_type=geoalchemy2.types.Geometry(geometry_type='LINESTRING', dimension=2, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               type_=geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=3857, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wall', 'geom',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=3857, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'),
               type_=geoalchemy2.types.Geometry(geometry_type='LINESTRING', dimension=2, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               existing_nullable=True)
    op.alter_column('node', 'geom',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POINT', srid=3857, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'),
               type_=geoalchemy2.types.Geometry(geometry_type='POINT', dimension=2, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               existing_nullable=True)
    # ### end Alembic commands ###
